# This workflow is disabled as we're using GitHub Pages instead
# To re-enable, remove the comments and update as needed

name: Deploy to Netlify (Disabled)

on:
  # Disabled workflow won't run automatically
  # push:
  #   branches:
  #     - main
  workflow_dispatch:  # Manual trigger only

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '16'
      
      - name: Deploy to Netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        with:
          args: deploy --dir=. --prod
          secrets: '["SUPABASE_URL", "SUPABASE_KEY"]' 