name: Direct Deploy to GitHub Pages

on:
  workflow_dispatch:
    inputs:
      debug:
        description: 'Enable debug mode'
        required: false
        default: 'false'

jobs:
  direct-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Show current branch
        run: |
          echo "Current branch: $(git rev-parse --abbrev-ref HEAD)"
          echo "Current commit: $(git rev-parse HEAD)"
          
      - name: Show GitHub Pages settings
        run: |
          echo "GitHub repository: ${{ github.repository }}"
          echo "GitHub Actor: ${{ github.actor }}"
          echo "Repository visibility: Public"
          
      - name: Create direct test files
        run: |
          cat > direct-test2.html << EOF
          <!DOCTYPE html>
          <html>
          <head>
              <title>Direct Deploy Test</title>
              <style>
                  body { font-family: Arial; max-width: 800px; margin: 20px auto; padding: 20px; }
                  .success { color: green; font-weight: bold; }
                  .error { color: red; font-weight: bold; }
              </style>
          </head>
          <body>
              <h1>Direct Deploy Test</h1>
              <p>This page was created directly by the GitHub Action workflow.</p>
              <p>Timestamp: $(date)</p>
              <p>Build ID: ${{ github.run_id }}</p>
              <p>Workflow Name: ${{ github.workflow }}</p>
          </body>
          </html>
          EOF
          echo "Created direct-test2.html"
          
          # Create basic config.js file
          echo "// Config file created by Direct Deploy" > config.js
          echo "const config = {" >> config.js
          echo "    supabaseUrl: 'https://peaphqbxdmknxzsfdxuh.supabase.co'," >> config.js
          echo "    supabaseKey: '${{ secrets.SUPABASE_ANON_KEY }}'" >> config.js
          echo "};" >> config.js
          echo "Created config.js with key: $(grep -c supabaseKey config.js) reference"
          cat config.js | grep -v supabaseKey
          
      - name: List files to be deployed
        run: |
          echo "Files to be deployed:"
          find . -type f -not -path "*/\.*" | sort
          echo "Total files: $(find . -type f -not -path "*/\.*" | wc -l)"
          
      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Ensure .nojekyll exists
        run: |
          touch .nojekyll
          echo "Created .nojekyll file"
          
      - name: Ensure CNAME exists
        run: |
          echo "www.padelpals.app" > CNAME
          echo "Created CNAME file with: $(cat CNAME)"
          
      - name: Deploy direct to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          branch: gh-pages
          clean: false  # Don't clean existing files
          commit-message: "Direct deploy for testing [skip ci]" 